theme = "my_mocha"

[editor]
line-number = "absolute"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
git-ignore = false

[keys.normal.space]
# 'space + n' pour masquer les numéros (n comme "No numbers")
n = [":set gutters.layout [\"diagnostics\",\"spacer\",\"diff\"]"]
# 'space + l' pour réafficher les numéros (l comme "Line numbers")
l = [":set gutters.layout [\"diagnostics\",\"line-numbers\",\"spacer\",\"diff\"]"]
