[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.jedi-language-server]
command = "jedi-language-server"

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci", "-sr"] }

[[language]]
name = "markdown"
auto-format = true
language-servers = []
formatter = { command = "mdformat", args = ["-"] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["ruff", "jedi-language-server"]

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m", "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]

[language.debugger.templates.args]
mode = "debug"
program = "{0}"

[[language]]
name = "json"
auto-format = true
formatter = { command = "jq", args = ["."] }
